### ISSUE TITLE
Cara Atasi nya

### ISSUE THREAD

**Issue by JereGanz342** [Urbaeexyz/whatsapp-bot#30]
![image](https://user-images.githubusercontent.com/82394685/117945267-5e813a80-b338-11eb-9900-9888448dc1bb.png)

**Comment by JereGanz342** [comment]
HELP MEEEE

**Comment by Urbaeexyz** [comment]
> HELP MEEEE

`npm i --save @open-wa/wa-automate@latest

**Comment by Urbaeexyz** [comment]
klo masih error, usahain pake nodejs versi 14
