### ISSUE TITLE
[EROR] ReferenceError: isRegistered is not defined

### ISSUE THREAD

**Issue by AomineHG** [Urbaeexyz/whatsapp-bot#57]
![image](https://user-images.githubusercontent.com/66240874/129438856-ee36078f-36d8-434d-8c56-80df6d87e06a.png)
kenapa ni bang ?

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129438856-ee36078f-36d8-434d-8c56-80df6d87e06a.png)
> kenapa ni bang ?

bntr

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129438856-ee36078f-36d8-434d-8c56-80df6d87e06a.png)
> kenapa ni bang ?

coba screenshot line di HandleMsg.js Line 463

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129438856-ee36078f-36d8-434d-8c56-80df6d87e06a.png)
> kenapa ni bang ?

perasaan dah dihapus deh `isRegistered`
[nih coba liat](https://github.com/Urbaeexyz/whatsapp-bot/commit/829946287e85007843cb5b68b512c2d8a183ac2a)

**Comment by Urbaeexyz** [comment]
`git clone https://github.com/Urbaeexyz/whatsapp-bot`

dah ganti nama repo

**Comment by AomineHG** [comment]
![image](https://user-images.githubusercontent.com/66240874/129441856-b0492ec4-9d46-433b-81bf-d11895d3ffe6.png)
sama ini bang, fotonya gada tapi erorr gitu
oh iya  fitur doujin dan ph erorr juga

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129441856-b0492ec4-9d46-433b-81bf-d11895d3ffe6.png)
> sama ini bang, fotonya gada tapi erorr gitu
> oh iya fitur doujin dan ph erorr juga

doujin errornya dmn?
phsearch dah aing delete

**Comment by AomineHG** [comment]
![image](https://user-images.githubusercontent.com/66240874/129442121-43f0c00d-d655-43e0-9ce3-8d796fcef916.png)
ini masalah api atau gimana bang ?
oiya  pp level gimana tu ?

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129442121-43f0c00d-d655-43e0-9ce3-8d796fcef916.png)
> ini masalah api atau gimana bang ?
> oiya pp level gimana tu ?

itu ga maslaah api
url thumbnailnya ga bisa di server indo, di block
gw ganti jadi ga pake thumbnail aja ye

**Comment by AomineHG** [comment]
ok,  oiya errorImg levelnya :v

**Comment by Urbaeexyz** [comment]
> ok, oiya errorImg levelnya :v

canvacord udh didownload?

**Comment by AomineHG** [comment]
gataw kayak belum

**Comment by Urbaeexyz** [comment]
> gataw kayak belum
`npm i --save canvacord@latest`

ini yg doujin coba ganti ke [ini](https://github.com/Urbaeexyz/whatsapp-bot/commit/8db6e486471bddda16e2c0061c3e6e4e5b494345)

**Comment by Urbaeexyz** [comment]
> gataw kayak belum

coba pake command ini
`npm i --save canvacord`

yg doujin ganti line yg [ini](https://github.com/Urbaeexyz/whatsapp-bot/commit/8db6e486471bddda16e2c0061c3e6e4e5b494345)

**Comment by AomineHG** [comment]
okok makasih bang

**Comment by AomineHG** [comment]
eh masih bang

**Comment by AomineHG** [comment]
yang canvacord masih gabisa

**Comment by Urbaeexyz** [comment]
> yang canvacord masih gabisa

gabisa gmn?
coba ss

**Comment by AomineHG** [comment]
![image](https://user-images.githubusercontent.com/66240874/129442649-6ef6c69d-5552-45f1-be56-7421ee119c80.png)
sama aja  padahal udah instal canavacord

**Comment by Urbaeexyz** [comment]
> ![image](https://user-images.githubusercontent.com/66240874/129442649-6ef6c69d-5552-45f1-be56-7421ee119c80.png)
> sama aja padahal udah instal canavacord

coba ganti ke ini

`case prefix+'level':
                if (!isLevelingOn) return await aruga.reply(from, 'Fitur Leveling belum diaktifkan!', id)
                if (!isGroupMsg) return await aruga.reply(from, 'Fitur ini hanya bisa digunakan didalam Grup!', id)
                const userLevel = level.getLevelingLevel(sender.id, _level)
                const userXp = level.getLevelingXp(sender.id, _level)
                const ppLink = await aruga.getProfilePicFromServer(sender.id)
                if (ppLink === undefined) {
                    var pepe = errorImg
                } else {
                    pepe = ppLink
                }
                const requiredXp = 5 * Math.pow(userLevel, 2) + 50 * userLevel + 100
                const rank = new canvas.Rank()
                    .setAvatar(pepe)
                    .setLevel(userLevel)
                    .setLevelColor('#ffa200', '#ffa200')
                    .setRank(Number(level.getUserRank(sender.id, _level)))
                    .setCurrentXP(userXp)
                    .setOverlay('#000000', 100, false)
                    .setRequiredXP(requiredXp)
                    .setProgressBar('#ffa200', 'COLOR')
                    .setBackground('COLOR', '#000000')
                    .setUsername(pushname)
                    .setDiscriminator(sender.id.substring(6, 10))
                rank.build()
                    .then(async (buffer) => {
						canvas.write(buffer, `${sender.id}_level.png`)
                        await aruga.sendFile(from, `${sender.id}_level.png`, `${sender.id}_level.png`, '', id)
						fs.unlinkSync(`${sender.id}_wanted.png`)
                    })
                    .catch(async (err) => {
                        console.error(err)
                        await aruga.reply(from, 'Error!', id)
                    })
            break
`

**Comment by AomineHG** [comment]
masih erorr wakwkakkwa

**Comment by Urbaeexyz** [comment]
> masih erorr wakwkakkwa

bntr gw coba dlu

**Comment by Urbaeexyz** [comment]
> masih erorr wakwkakkwa

ada wa ga?

**Comment by AomineHG** [comment]
ada bang

**Comment by Urbaeexyz** [comment]
> ada bang

ntarr, ini susahnya kalo gada hp nih wkwk

**Comment by Urbaeexyz** [comment]
> ada bang

leveling udah bisa tuh
gw close ya
