### ISSUE TITLE
ERROR TimeoutError: Navigation timeout of 30000 ms exceeded

### ISSUE THREAD

**Issue by ManZipp** [Urbaeexyz/whatsapp-bot#71]
Error ini kenape ye bang? ada solusi?

![gambar](https://user-images.githubusercontent.com/89239856/130229042-25430f6d-a542-4f73-9747-4efa62ec9910.png)

**Comment by Urbaeexyz** [comment]
> Error ini kenape ye bang? ada solusi?
> 
> ![gambar](https://user-images.githubusercontent.com/89239856/130229042-25430f6d-a542-4f73-9747-4efa62ec9910.png)

jaringan?

**Comment by ManZipp** [comment]
> 
> 
> > Error ini kenape ye bang? ada solusi?
> > ![gambar](https://user-images.githubusercontent.com/89239856/130229042-25430f6d-a542-4f73-9747-4efa62ec9910.png)
> 
> jaringan?

aman bro kalo jaringan saya coba di vps juga sama

**Comment by Urbaeexyz** [comment]
> > > Error ini kenape ye bang? ada solusi?
> > > ![gambar](https://user-images.githubusercontent.com/89239856/130229042-25430f6d-a542-4f73-9747-4efa62ec9910.png)
> > 
> > 
> > jaringan?
> 
> aman bro kalo jaringan saya coba di vps juga sama

update ke terbaru

`npm i --save @open-wa/wa-automate@latest`

**Comment by Urbaeexyz** [comment]
udah bisa?

**Comment by ManZipp** [comment]
masih bro

**Comment by Urbaeexyz** [comment]
> masih bro

jaringan deh
gw bisa aja
![image](https://user-images.githubusercontent.com/75126993/130245596-80df956e-5304-458a-a5df-0d67fada1a9b.png)

**Comment by ManZipp** [comment]
udah bisa bro

**Comment by Urbaeexyz** [comment]
> udah bisa bro ternyata pas coba di vps bisa walau ada beberapa eror tapi udah ke fix

okee
btw error kek gmna ya?
