### ISSUE TITLE
Error in #level and #mystat

### ISSUE THREAD

**Issue by Stive889** [Urbaeexyz/whatsapp-bot#72]
**hi thoriq, I have an error (only in some users) when they write #level it gives the following error:**

'Error: ENOENT, No such file or directory 'ERROR: 401'
    at setSource (/home/bruno/wa-bot/node_modules/canvas/lib/image.js:91:13)
    at Image.set (/home/bruno/wa-bot/node_modules/canvas/lib/image.js:62:9)
    at /home/bruno/wa-bot/node_modules/canvas/index.js:34:15
    at new Promise (<anonymous>)
    at Object.loadImage (/home/bruno/wa-bot/node_modules/canvas/index.js:23:10)
    at Rank.build (/home/bruno/wa-bot/node_modules/canvacord/src/Rank.js:477:35)
    at HandleMsg (/home/bruno/wa-bot/HandleMsg.js:1080:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  errno: 2,
  code: 'ENOENT',
  path: 'ERROR: 401',
  syscall: 'fopen'
}'
**when they write #mystat it gives the following error.**

'node:internal/process/promises:245
          triggerUncaughtException(err, true /* fromPromise */);
          ^

<ref *1> Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 80,
  config: {
    url: 'ERROR: 401',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      DNT: 1,
      'Upgrade-Insecure-Requests': 1,
      'User-Agent': 'axios/0.21.1'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *3> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: 10485760,
      protocol: 'http:',
      path: '%20401',
      method: 'GET',
      headers: {
        Accept: 'application/json, text/plain, */*',
        DNT: 1,
        'Upgrade-Insecure-Requests': 1,
        'User-Agent': 'axios/0.21.1'
      },
      agent: undefined,
      agents: { http: undefined, https: undefined },
      auth: undefined,
      hostname: '',
      port: null,
      nativeProtocols: {
        'http:': {
          _connectionListener: [Function: connectionListener],
          METHODS: [
            'ACL',        'BIND',        'CHECKOUT',
            'CONNECT',    'COPY',        'DELETE',
            'GET',        'HEAD',        'LINK',
            'LOCK',       'M-SEARCH',    'MERGE',
            'MKACTIVITY', 'MKCALENDAR',  'MKCOL',
            'MOVE',       'NOTIFY',      'OPTIONS',
            'PATCH',      'POST',        'PRI',
            'PROPFIND',   'PROPPATCH',   'PURGE',
            'PUT',        'REBIND',      'REPORT',
            'SEARCH',     'SOURCE',      'SUBSCRIBE',
            'TRACE',      'UNBIND',      'UNLINK',
            'UNLOCK',     'UNSUBSCRIBE'
          ],
          STATUS_CODES: {
            '100': 'Continue',
            '101': 'Switching Protocols',
            '102': 'Processing',
            '103': 'Early Hints',
            '200': 'OK',
            '201': 'Created',
            '202': 'Accepted',
            '203': 'Non-Authoritative Information',
            '204': 'No Content',
            '205': 'Reset Content',
            '206': 'Partial Content',
            '207': 'Multi-Status',
            '208': 'Already Reported',
            '226': 'IM Used',
            '300': 'Multiple Choices',
            '301': 'Moved Permanently',
            '302': 'Found',
            '303': 'See Other',
            '304': 'Not Modified',
            '305': 'Use Proxy',
            '307': 'Temporary Redirect',
            '308': 'Permanent Redirect',
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a Teapot",
            '421': 'Misdirected Request',
            '422': 'Unprocessable Entity',
            '423': 'Locked',
            '424': 'Failed Dependency',
            '425': 'Too Early',
            '426': 'Upgrade Required',
            '428': 'Precondition Required',
            '429': 'Too Many Requests',
            '431': 'Request Header Fields Too Large',
            '451': 'Unavailable For Legal Reasons',
            '500': 'Internal Server Error',
            '501': 'Not Implemented',
            '502': 'Bad Gateway',
            '503': 'Service Unavailable',
            '504': 'Gateway Timeout',
            '505': 'HTTP Version Not Supported',
            '506': 'Variant Also Negotiates',
            '507': 'Insufficient Storage',
            '508': 'Loop Detected',
            '509': 'Bandwidth Limit Exceeded',
            '510': 'Not Extended',
            '511': 'Network Authentication Required'
          },
          Agent: [Function: Agent] { defaultMaxSockets: Infinity },
          ClientRequest: [Function: ClientRequest],
          IncomingMessage: [Function: IncomingMessage],
          OutgoingMessage: [Function: OutgoingMessage],
          Server: [Function: Server],
          ServerResponse: [Function: ServerResponse],
          createServer: [Function: createServer],
          validateHeaderName: [Function: __node_internal_],
          validateHeaderValue: [Function: __node_internal_],
          get: [Function: get],
          request: [Function: request],
          maxHeaderSize: [Getter],
          globalAgent: [Getter/Setter]
        },
        'https:': {
          Agent: [Function: Agent],
          globalAgent: Agent {
            _events: [Object: null prototype],
            _eventsCount: 2,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object],
            requests: {},
            sockets: {},
            freeSockets: {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            scheduling: 'lifo',
            maxTotalSockets: Infinity,
            totalSocketCount: 0,
            maxCachedSessions: 100,
            _sessionCache: [Object],
            [Symbol(kCapture)]: false
          },
          Server: [Function: Server],
          createServer: [Function: createServer],
          get: [Function: get],
          request: [Function: request]
        }
      },
      pathname: '%20401'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: <ref *2> ClientRequest {
      _events: [Object: null prototype] {
        response: [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: Socket {
        connecting: false,
        _hadError: true,
        _parent: null,
        _host: 'localhost',
        _readableState: ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          destroyed: true,
          errored: [Circular *1],
          closed: true,
          closeEmitted: true,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _events: [Object: null prototype] {
          end: [Function: onReadableStreamEnd],
          connect: [ [Function], [Function], [Function] ],
          free: [Function: onFree],
          close: [ [Function: onClose], [Function: socketCloseListener] ],
          timeout: [Function: onTimeout],
          agentRemove: [Function: onRemove],
          error: [Function: socketErrorListener],
          drain: [Function: ondrain]
        },
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 166,
          writing: true,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: [Function: bound onFinish],
          writelen: 166,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 1,
          constructed: true,
          prefinished: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          errored: [Circular *1],
          closed: true,
          closeEmitted: true,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: 'GET %20401 HTTP/1.1\r\n' +
          'Accept: application/json, text/plain, */*\r\n' +
          'DNT: 1\r\n' +
          'Upgrade-Insecure-Requests: 1\r\n' +
          'User-Agent: axios/0.21.1\r\n' +
          'Host: localhost\r\n' +
          'Connection: close\r\n' +
          '\r\n',
        _pendingEncoding: 'latin1',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular *2],
        [Symbol(async_id_symbol)]: 4069,
        [Symbol(kHandle)]: null,
        [Symbol(kSetNoDelay)]: false,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      _header: 'GET %20401 HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'DNT: 1\r\n' +
        'Upgrade-Insecure-Requests: 1\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Host: localhost\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: {},
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: { path: null },
        requests: {},
        sockets: { 'localhost:80:': [ [Socket] ] },
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '%20401',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *3],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        dnt: [ 'DNT', 1 ],
        'upgrade-insecure-requests': [ 'Upgrade-Insecure-Requests', 1 ],
        'user-agent': [ 'User-Agent', 'axios/0.21.1' ],
        host: [ 'Host', 'localhost' ]
      }
    },
    _currentUrl: 'http:%20401',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function: toJSON]
}'

**I asked them to remove the username from ws or remove special characters to test if it was this, but no, they are not blocked from the bot or anything like that either.

do you have any idea?

PS: I use Ubuntu**

**Comment by Urbaeexyz** [comment]
> **hi thoriq, I have an error (only in some users) when they write #level it gives the following error:**
> 
> 'Error: ENOENT, No such file or directory 'ERROR: 401'
> at setSource (/home/bruno/wa-bot/node_modules/canvas/lib/image.js:91:13)
> at Image.set (/home/bruno/wa-bot/node_modules/canvas/lib/image.js:62:9)
> at /home/bruno/wa-bot/node_modules/canvas/index.js:34:15
> at new Promise ()
> at Object.loadImage (/home/bruno/wa-bot/node_modules/canvas/index.js:23:10)
> at Rank.build (/home/bruno/wa-bot/node_modules/canvacord/src/Rank.js:477:35)
> at HandleMsg (/home/bruno/wa-bot/HandleMsg.js:1080:11)
> at processTicksAndRejections (node:internal/process/task_queues:94:5) {
> errno: 2,
> code: 'ENOENT',
> path: 'ERROR: 401',
> syscall: 'fopen'
> }'
> **when they write #mystat it gives the following error.**
> 
> 'node:internal/process/promises:245
> triggerUncaughtException(err, true /* fromPromise */);
> ^
> 
> <ref *1> Error: connect ECONNREFUSED 127.0.0.1:80
> at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {
> errno: -111,
> code: 'ECONNREFUSED',
> syscall: 'connect',
> address: '127.0.0.1',
> port: 80,
> config: {
> url: 'ERROR: 401',
> method: 'get',
> headers: {
> Accept: 'application/json, text/plain, _/_',
> DNT: 1,
> 'Upgrade-Insecure-Requests': 1,
> 'User-Agent': 'axios/0.21.1'
> },
> transformRequest: [ [Function: transformRequest] ],
> transformResponse: [ [Function: transformResponse] ],
> timeout: 0,
> adapter: [Function: httpAdapter],
> responseType: 'arraybuffer',
> xsrfCookieName: 'XSRF-TOKEN',
> xsrfHeaderName: 'X-XSRF-TOKEN',
> maxContentLength: -1,
> maxBodyLength: -1,
> validateStatus: [Function: validateStatus],
> data: undefined
> },
> request: <ref *3> Writable {
> _writableState: WritableState {
> objectMode: false,
> highWaterMark: 16384,
> finalCalled: false,
> needDrain: false,
> ending: false,
> ended: false,
> finished: false,
> destroyed: false,
> decodeStrings: true,
> defaultEncoding: 'utf8',
> length: 0,
> writing: false,
> corked: 0,
> sync: true,
> bufferProcessing: false,
> onwrite: [Function: bound onwrite],
> writecb: null,
> writelen: 0,
> afterWriteTickInfo: null,
> buffered: [],
> bufferedIndex: 0,
> allBuffers: true,
> allNoop: true,
> pendingcb: 0,
> constructed: true,
> prefinished: false,
> errorEmitted: false,
> emitClose: true,
> autoDestroy: true,
> errored: null,
> closed: false,
> closeEmitted: false,
> [Symbol(kOnFinished)]: []
> },
> _events: [Object: null prototype] {
> response: [Function: handleResponse],
> error: [Function: handleRequestError]
> },
> _eventsCount: 2,
> _maxListeners: undefined,
> _options: {
> maxRedirects: 21,
> maxBodyLength: 10485760,
> protocol: 'http:',
> path: '%20401',
> method: 'GET',
> headers: {
> Accept: 'application/json, text/plain, _/_',
> DNT: 1,
> 'Upgrade-Insecure-Requests': 1,
> 'User-Agent': 'axios/0.21.1'
> },
> agent: undefined,
> agents: { http: undefined, https: undefined },
> auth: undefined,
> hostname: '',
> port: null,
> nativeProtocols: {
> 'http:': {
> _connectionListener: [Function: connectionListener],
> METHODS: [
> 'ACL', 'BIND', 'CHECKOUT',
> 'CONNECT', 'COPY', 'DELETE',
> 'GET', 'HEAD', 'LINK',
> 'LOCK', 'M-SEARCH', 'MERGE',
> 'MKACTIVITY', 'MKCALENDAR', 'MKCOL',
> 'MOVE', 'NOTIFY', 'OPTIONS',
> 'PATCH', 'POST', 'PRI',
> 'PROPFIND', 'PROPPATCH', 'PURGE',
> 'PUT', 'REBIND', 'REPORT',
> 'SEARCH', 'SOURCE', 'SUBSCRIBE',
> 'TRACE', 'UNBIND', 'UNLINK',
> 'UNLOCK', 'UNSUBSCRIBE'
> ],
> STATUS_CODES: {
> '100': 'Continue',
> '101': 'Switching Protocols',
> '102': 'Processing',
> '103': 'Early Hints',
> '200': 'OK',
> '201': 'Created',
> '202': 'Accepted',
> '203': 'Non-Authoritative Information',
> '204': 'No Content',
> '205': 'Reset Content',
> '206': 'Partial Content',
> '207': 'Multi-Status',
> '208': 'Already Reported',
> '226': 'IM Used',
> '300': 'Multiple Choices',
> '301': 'Moved Permanently',
> '302': 'Found',
> '303': 'See Other',
> '304': 'Not Modified',
> '305': 'Use Proxy',
> '307': 'Temporary Redirect',
> '308': 'Permanent Redirect',
> '400': 'Bad Request',
> '401': 'Unauthorized',
> '402': 'Payment Required',
> '403': 'Forbidden',
> '404': 'Not Found',
> '405': 'Method Not Allowed',
> '406': 'Not Acceptable',
> '407': 'Proxy Authentication Required',
> '408': 'Request Timeout',
> '409': 'Conflict',
> '410': 'Gone',
> '411': 'Length Required',
> '412': 'Precondition Failed',
> '413': 'Payload Too Large',
> '414': 'URI Too Long',
> '415': 'Unsupported Media Type',
> '416': 'Range Not Satisfiable',
> '417': 'Expectation Failed',
> '418': "I'm a Teapot",
> '421': 'Misdirected Request',
> '422': 'Unprocessable Entity',
> '423': 'Locked',
> '424': 'Failed Dependency',
> '425': 'Too Early',
> '426': 'Upgrade Required',
> '428': 'Precondition Required',
> '429': 'Too Many Requests',
> '431': 'Request Header Fields Too Large',
> '451': 'Unavailable For Legal Reasons',
> '500': 'Internal Server Error',
> '501': 'Not Implemented',
> '502': 'Bad Gateway',
> '503': 'Service Unavailable',
> '504': 'Gateway Timeout',
> '505': 'HTTP Version Not Supported',
> '506': 'Variant Also Negotiates',
> '507': 'Insufficient Storage',
> '508': 'Loop Detected',
> '509': 'Bandwidth Limit Exceeded',
> '510': 'Not Extended',
> '511': 'Network Authentication Required'
> },
> Agent: [Function: Agent] { defaultMaxSockets: Infinity },
> ClientRequest: [Function: ClientRequest],
> IncomingMessage: [Function: IncomingMessage],
> OutgoingMessage: [Function: OutgoingMessage],
> Server: [Function: Server],
> ServerResponse: [Function: ServerResponse],
> createServer: [Function: createServer],
> validateHeaderName: [Function: __node_internal_],
> validateHeaderValue: [Function: __node_internal_],
> get: [Function: get],
> request: [Function: request],
> maxHeaderSize: [Getter],
> globalAgent: [Getter/Setter]
> },
> 'https:': {
> Agent: [Function: Agent],
> globalAgent: Agent {
> _events: [Object: null prototype],
> _eventsCount: 2,
> _maxListeners: undefined,
> defaultPort: 443,
> protocol: 'https:',
> options: [Object],
> requests: {},
> sockets: {},
> freeSockets: {},
> keepAliveMsecs: 1000,
> keepAlive: false,
> maxSockets: Infinity,
> maxFreeSockets: 256,
> scheduling: 'lifo',
> maxTotalSockets: Infinity,
> totalSocketCount: 0,
> maxCachedSessions: 100,
> _sessionCache: [Object],
> [Symbol(kCapture)]: false
> },
> Server: [Function: Server],
> createServer: [Function: createServer],
> get: [Function: get],
> request: [Function: request]
> }
> },
> pathname: '%20401'
> },
> _ended: true,
> _ending: true,
> _redirectCount: 0,
> _redirects: [],
> _requestBodyLength: 0,
> _requestBodyBuffers: [],
> _onNativeResponse: [Function (anonymous)],
> _currentRequest: <ref *2> ClientRequest {
> _events: [Object: null prototype] {
> response: [Function: bound onceWrapper] {
> listener: [Function (anonymous)]
> },
> abort: [Function (anonymous)],
> aborted: [Function (anonymous)],
> connect: [Function (anonymous)],
> error: [Function (anonymous)],
> socket: [Function (anonymous)],
> timeout: [Function (anonymous)]
> },
> _eventsCount: 7,
> _maxListeners: undefined,
> outputData: [],
> outputSize: 0,
> writable: true,
> destroyed: false,
> _last: true,
> chunkedEncoding: false,
> shouldKeepAlive: false,
> _defaultKeepAlive: true,
> useChunkedEncodingByDefault: false,
> sendDate: false,
> _removedConnection: false,
> _removedContLen: false,
> _removedTE: false,
> _contentLength: 0,
> _hasBody: true,
> _trailer: '',
> finished: true,
> _headerSent: true,
> _closed: false,
> socket: Socket {
> connecting: false,
> _hadError: true,
> _parent: null,
> _host: 'localhost',
> _readableState: ReadableState {
> objectMode: false,
> highWaterMark: 16384,
> buffer: BufferList { head: null, tail: null, length: 0 },
> length: 0,
> pipes: [],
> flowing: true,
> ended: false,
> endEmitted: false,
> reading: true,
> constructed: true,
> sync: false,
> needReadable: true,
> emittedReadable: false,
> readableListening: false,
> resumeScheduled: false,
> errorEmitted: true,
> emitClose: false,
> autoDestroy: true,
> destroyed: true,
> errored: [Circular *1],
> closed: true,
> closeEmitted: true,
> defaultEncoding: 'utf8',
> awaitDrainWriters: null,
> multiAwaitDrain: false,
> readingMore: false,
> decoder: null,
> encoding: null,
> [Symbol(kPaused)]: false
> },
> _events: [Object: null prototype] {
> end: [Function: onReadableStreamEnd],
> connect: [ [Function], [Function], [Function] ],
> free: [Function: onFree],
> close: [ [Function: onClose], [Function: socketCloseListener] ],
> timeout: [Function: onTimeout],
> agentRemove: [Function: onRemove],
> error: [Function: socketErrorListener],
> drain: [Function: ondrain]
> },
> _eventsCount: 8,
> _maxListeners: undefined,
> _writableState: WritableState {
> objectMode: false,
> highWaterMark: 16384,
> finalCalled: false,
> needDrain: false,
> ending: false,
> ended: false,
> finished: false,
> destroyed: true,
> decodeStrings: false,
> defaultEncoding: 'utf8',
> length: 166,
> writing: true,
> corked: 0,
> sync: false,
> bufferProcessing: false,
> onwrite: [Function: bound onwrite],
> writecb: [Function: bound onFinish],
> writelen: 166,
> afterWriteTickInfo: null,
> buffered: [],
> bufferedIndex: 0,
> allBuffers: true,
> allNoop: true,
> pendingcb: 1,
> constructed: true,
> prefinished: false,
> errorEmitted: true,
> emitClose: false,
> autoDestroy: true,
> errored: [Circular *1],
> closed: true,
> closeEmitted: true,
> [Symbol(kOnFinished)]: []
> },
> allowHalfOpen: false,
> _sockname: null,
> _pendingData: 'GET %20401 HTTP/1.1\r\n' +
> 'Accept: application/json, text/plain, _/_\r\n' +
> 'DNT: 1\r\n' +
> 'Upgrade-Insecure-Requests: 1\r\n' +
> 'User-Agent: axios/0.21.1\r\n' +
> 'Host: localhost\r\n' +
> 'Connection: close\r\n' +
> '\r\n',
> _pendingEncoding: 'latin1',
> server: null,
> _server: null,
> parser: null,
> _httpMessage: [Circular *2],
> [Symbol(async_id_symbol)]: 4069,
> [Symbol(kHandle)]: null,
> [Symbol(kSetNoDelay)]: false,
> [Symbol(lastWriteQueueSize)]: 0,
> [Symbol(timeout)]: null,
> [Symbol(kBuffer)]: null,
> [Symbol(kBufferCb)]: null,
> [Symbol(kBufferGen)]: null,
> [Symbol(kCapture)]: false,
> [Symbol(kBytesRead)]: 0,
> [Symbol(kBytesWritten)]: 0
> },
> _header: 'GET %20401 HTTP/1.1\r\n' +
> 'Accept: application/json, text/plain, _/_\r\n' +
> 'DNT: 1\r\n' +
> 'Upgrade-Insecure-Requests: 1\r\n' +
> 'User-Agent: axios/0.21.1\r\n' +
> 'Host: localhost\r\n' +
> 'Connection: close\r\n' +
> '\r\n',
> _keepAliveTimeout: 0,
> _onPendingData: {},
> agent: Agent {
> _events: [Object: null prototype] {
> free: [Function (anonymous)],
> newListener: [Function: maybeEnableKeylog]
> },
> _eventsCount: 2,
> _maxListeners: undefined,
> defaultPort: 80,
> protocol: 'http:',
> options: { path: null },
> requests: {},
> sockets: { 'localhost:80:': [ [Socket] ] },
> freeSockets: {},
> keepAliveMsecs: 1000,
> keepAlive: false,
> maxSockets: Infinity,
> maxFreeSockets: 256,
> scheduling: 'lifo',
> maxTotalSockets: Infinity,
> totalSocketCount: 1,
> [Symbol(kCapture)]: false
> },
> socketPath: undefined,
> method: 'GET',
> maxHeaderSize: undefined,
> insecureHTTPParser: undefined,
> path: '%20401',
> _ended: false,
> res: null,
> aborted: false,
> timeoutCb: null,
> upgradeOrConnect: false,
> parser: null,
> maxHeadersCount: null,
> reusedSocket: false,
> host: 'localhost',
> protocol: 'http:',
> _redirectable: [Circular *3],
> [Symbol(kCapture)]: false,
> [Symbol(kNeedDrain)]: false,
> [Symbol(corked)]: 0,
> [Symbol(kOutHeaders)]: [Object: null prototype] {
> accept: [ 'Accept', 'application/json, text/plain, _/_' ],
> dnt: [ 'DNT', 1 ],
> 'upgrade-insecure-requests': [ 'Upgrade-Insecure-Requests', 1 ],
> 'user-agent': [ 'User-Agent', 'axios/0.21.1' ],
> host: [ 'Host', 'localhost' ]
> }
> },
> _currentUrl: 'http:%20401',
> [Symbol(kCapture)]: false
> },
> response: undefined,
> isAxiosError: true,
> toJSON: [Function: toJSON]
> }'
> 
> **I asked them to remove the username from ws or remove special characters to test if it was this, but no, they are not blocked from the bot or anything like that either.
> 
> do you have any idea?
> 
> PS: I use Ubuntu**

<img src="https://instagram.fpnk3-1.fna.fbcdn.net/v/t51.2885-15/e35/p480x480/236696336_2774528919504833_4038939701895398843_n.jpg?_nc_ht=instagram.fpnk3-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=0mSZCJ29eWwAX8ztT55&edm=AJXOVykBAAAA&ccb=7-4&oh=33898fb9c5ba3a67fa2f7169252f2ef0&oe=61268570&_nc_sid=9c1db7&ig_cache_key=MjY0MjA2NDgxMDA4Mzg5NTUyMQ%3D%3D.2-ccb7-4">

**Comment by Urbaeexyz** [comment]
have a completely install all packages?

**Comment by Stive889** [comment]
I understand that, it works for many but only a few do they get that error

**Comment by Stive889** [comment]
I did the test with the previous version 2.5.5 (without making any changes to the code) and the error persists in #level #mystat and #me

**Comment by Urbaeexyz** [comment]
> I did the test with the previous version 2.5.5 (without making any changes to the code) and the error persists in #level #mystat and #me

sorry for that, for that feature i'm just copy and paste to my script
[see this](https://github.com/SlavyanDesu/BocchiBot)

**Comment by gamingrkp** [comment]
> I understand that, it works for many but only a few do they get that error

thats error will show if you not use profile picture, just try add profile picture and public profile

**Comment by Urbaeexyz** [comment]
> > I understand that, it works for many but only a few do they get that error
> 
> thats error will show if you not use profile picture, just try add profile picture then public profile

okay, wait

**Comment by Stive889** [comment]
I already did the test, and if that's what it is, since the bot has the photo, it sends the commands, couldn't you put a default image for those cases? and no error?

**Comment by Urbaeexyz** [comment]
> I already did the test, and if that's what it is, since the bot has the photo, it sends the commands, couldn't you put a default image for those cases? and no error?

i think it's already catch if it's error on profile

**Comment by Urbaeexyz** [comment]
> I already did the test, and if that's what it is, since the bot has the photo, it sends the commands, couldn't you put a default image for those cases? and no error?

https://github.com/Urbaeexyz/whatsapp-bot/commit/5c2e4a58c1c5d0b157b28a9ec8abea243548226e

**Comment by Stive889** [comment]
I did the test, and the change did not work in the three commands

**Comment by gamingrkp** [comment]
> > I already did the test, and if that's what it is, since the bot has the photo, it sends the commands, couldn't you put a default image for those cases? and no error?
> 
> [5c2e4a5](https://github.com/Urbaeexyz/whatsapp-bot/commit/5c2e4a58c1c5d0b157b28a9ec8abea243548226e)
`const ppLink = await aruga.getProfilePicFromServer(serial)
if (ppLink === `ERROR: 401`) {`

**Comment by gamingrkp** [comment]
> I did the test, and the change did not work in the three commands

work ?? use owner

**Comment by Urbaeexyz** [comment]
> I did the test, and the change did not work in the three commands

try use [this](https://github.com/Urbaeexyz/whatsapp-bot/commit/00366c013c04cf7c5e3b232ba41b2c7827dfb3e3)
if it's worked, pls tell me, if it's not tell me too:v

**Comment by Stive889** [comment]
it works correctly in mystat and level, you just need to copy the same code in me

**Comment by Urbaeexyz** [comment]
> hi, sorry for the response time, it works fine in mystat and level, you just need to copy the same code in me

where?

**Comment by Stive889** [comment]
case prefix+'me': 

I already changed it but so that it is in the main code

just modify this:  if (pic == 'ERROR: 401') {
