### ISSUE TITLE
Image to URL Error...

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/whatsapp-bot#73]
![Screenshot (66)](https://user-images.githubusercontent.com/76943884/130320040-a64315e2-abd0-4047-927c-ea655ce04860.png)

**Comment by Harsh-beep** [comment]
idk it started working

**Comment by Urbaeexyz** [comment]
> idk it started working

LMAOOOO

**Comment by Urbaeexyz** [comment]
> idk it started working

just wait if it's error
it's error bcause rest api itself

**Comment by Harsh-beep** [comment]
yea i got that when it automatically got fixed..lol
