### ISSUE TITLE
Identifier 'resultdata' has already been declared.

### ISSUE THREAD

**Issue by Harsh-beep** [Urbaeexyz/whatsapp-bot#74]
![Screenshot (67)](https://user-images.githubusercontent.com/76943884/130321439-32ad0d8e-02f8-40fd-857c-100f6dc9d56c.png)
i know it's easy to fix but just to let you know...

**Comment by Urbaeexyz** [comment]
> ![Screenshot (67)](https://user-images.githubusercontent.com/76943884/130321439-32ad0d8e-02f8-40fd-857c-100f6dc9d56c.png)
> i know it's easy to fix but just to let you know...

thank you
