### ISSUE TITLE
Bug welcome

### ISSUE THREAD

**Issue by badriyatus123** [Urbaeexyz/whatsapp-bot#75]
Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
Terimakasih sebelum nya

![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)

**Comment by gamingrkp** [comment]
> Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> Terimakasih sebelum nya
> 
> ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)

yo ketemu lagi

**Comment by Urbaeexyz** [comment]
ohhh shit

**Comment by gamingrkp** [comment]
> ohhh shit

oke owner selamat bekerja

**Comment by Urbaeexyz** [comment]
> > ohhh shit
> 
> oke owner selamat bekerja

yee anying:v

**Comment by Urbaeexyz** [comment]
> Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> Terimakasih sebelum nya
> 
> ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)

coba screenshot file ini lib/database/welcome.json

**Comment by Urbaeexyz** [comment]
> Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> Terimakasih sebelum nya
> 
> ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)

itu fotonya emg gada?

**Comment by badriyatus123** [comment]
> 
> 
> > Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> > Terimakasih sebelum nya
> > ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)
> 
> coba screenshot file ini lib/database/welcome.json

![gambar](https://user-images.githubusercontent.com/87899416/130329430-6c46d6e2-eac7-459e-90f6-d6dbab754296.png)

**Comment by badriyatus123** [comment]
> 
> 
> > Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> > Terimakasih sebelum nya
> > ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)
> 
> itu fotonya emg gada?

itu saya sensor min foto orang soal nya hehe

**Comment by Urbaeexyz** [comment]
> > > Ga tau kenapa setelah saya coba tambahkan welcome pada grup,dan cmd bot saya restart ,setelah bot aktif dan di grup ada aktifitas pengunaan bot tiba tiba bot ngewelcome semua member yang ada di grup
> > > Terimakasih sebelum nya
> > > ![gambar](https://user-images.githubusercontent.com/87899416/130328633-5b9a49c1-8ca2-452a-8e5d-e02b135b7f76.png)
> > 
> > 
> > itu fotonya emg gada?
> 
> itu saya sensor min foto orang soal nya hehe

emg kadang bug si, cuman ga jarang amat, ntar juga ilang lagi
kalo ga ilang kabarin aja

**Comment by badriyatus123** [comment]
oke oke atau setiap reset cmd kita harus dalate database welcome ya?

**Comment by Urbaeexyz** [comment]
> oke oke atau setiap reset cmd kita harus dalate database welcome ya?

biarin aja, kecuali emg fitur itu mau dinonaktifin aja, baru delete

**Comment by badriyatus123** [comment]
> 
> 
> > oke oke atau setiap reset cmd kita harus dalate database welcome ya?
> 
> biarin aja, kecuali emg fitur itu mau dinonaktifin aja, baru delete

oke oke takut nya ada ratusan member di dalam grup ke tag semua kan kasian:v
oke lah thanks ya bro bro

**Comment by Urbaeexyz** [comment]
> > > oke oke atau setiap reset cmd kita harus dalate database welcome ya?
> > 
> > 
> > biarin aja, kecuali emg fitur itu mau dinonaktifin aja, baru delete
> 
> oke oke takut nya ada ratusan member di dalam grup ke tag semua kan kasian:v
> oke lah thanks ya bro bro

gw dulu pernah kek gitu
semua member, klo gasalh ratusan
alhasil keluar smua:v

**Comment by gamingrkp** [comment]
> oke oke atau setiap reset cmd kita harus dalate database welcome ya?

welcome disable aja sih klo gamau ribet soalnya gw pernah terjadi kek gini karena chat keapus jdi ke trigger botnya kek baru masuk grub itu, tapi welcome enable nya nyala jdi pas keluar grub welcome disable aja
